version: "3.5"
x-services-volume: &services-volume
  type: bind

services:
  loadbalancer:
    container_name: nginx
    build:
      context: ./nginx
    restart: always
    hostname: nginx
    networks:
      - docker_network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /home/data/certbot/www:/var/www/certbot
    environment:
      PrimaryDomain: ${PrimaryDomain}
  stable:
    container_name: stable
    image: aglide100/ds-landing-page:latest
    hostname: stable
    networks:
      - docker_network
    expose:
      - 80
  edge:
    container_name: edge
    image: aglide100/ds-landing-page:1.0
    hostname: edge
    networks:
      - docker_network
    expose:
      - 80

networks:
  docker_network:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
